spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_machine_db
    username: your_db_user
    password: your_db_password
  jpa:
    hibernate:
      ddl-auto: update  #
    show-sql: true
  cache:
    type: caffeine

swagger:
  enable: true

cache:
  caffeine:
    spec: maximumSize=1000, expireAfterWrite=1d
